NumPy, which stands for Numerical Python, is a powerful library in Python used for numerical and scientific computing.
It provides essential tools for working with large, multi-dimensional arrays and matrices of numerical data, along with a collection of mathematical functions to operate on these arrays.

Key Concept of Numpy:

N-Dimensional Arrays
The core feature of NumPy is its ndarray, a versatile container that holds elements of the same type.
This array can be one-dimensional (like a list), two-dimensional (like a matrix), or even more dimensions. It allows efficient storage and manipulation of numerical data.

NumPy supports a wide range of mathematical operations on arrays.
This includes basic arithmetic operations like addition and subtraction, as well as more complex functions like trigonometric calculations and logarithms.
These operations are performed element-wise, meaning the operations are applied to each element of the array.

Broadcasting
Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes.
It automatically adjusts the dimensions of the smaller array to match the dimensions of the larger array, so that operations can be performed seamlessly.

What is an array?
An array is a collection of items stored at contiguous memory locations.
It's like a list where you can keep multiple values, such as numbers or strings, in a single variable.

Python List vs Numpy Array
Python List: A Python list is a versatile container that can store elements of varying types and sizes. It's useful for general-purpose tasks but lacks efficiency for numerical computations.
NumPy Array: A NumPy array is designed for efficient numerical operations and supports large datasets with elements of a single type. It offers advanced mathematical functions and better performance for scientific computing.

In [2]:
import numpy as np
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [3]:
# Creating a 2D array of zeros
zeros_array = np.zeros ((3, 4))
# 3 rows and 4 column
print("Array of Zeros: \n", zeros_array)

Array of Zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# Creating a 1D array of ones
ones_array = np.ones(5)
print("Array of Ones:", ones_array)

Array of Ones: [1. 1. 1. 1. 1.]


In [5]:
# Creating an array with values from to 9
range_array = np.arange(10)
print("Range Array:", range_array)


Range Array: [0 1 2 3 4 5 6 7 8 9]


In [6]:
# Creating an array with 5 evenly spaced values between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [7]:
print("Shape of array_2d:", array_2d.shape)
print("Size of array_2d", array_2d.size)


Shape of array_2d: (2, 3)
Size of array_2d 6


In [8]:
print("Data type of array_2d:", array_2d.dtype)

Data type of array_2d: int32


Indexing with NumPy Arrays
Indexing allows you to access and manipulate specific elements within NumPy arrays. This notebook will guide you through indexing for both 1D and 2D arrays.


In [9]:

# Creating a 1D array
array_1d = np.array([10, 20, 30, 40, 50])
#Accessing the third element (index 2)
print("Element at index 2:", array_1d[2])

Element at index 2: 30


In [10]:

# Accessing the last element using negative indexing
print("Last element:", array_1d[-1])
# Accessing the second-to-Last element
print("Second-to-last element:", array_1d[-2])

Last element: 50
Second-to-last element: 40


In [11]:

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
# Accessing the element at row 1, column 2
print("Element at (1, 2):", array_2d [1, 2])

Element at (1, 2): 60


In [12]:
# Accessing the second row
print("Second row:", array_2d [1])
# Accessing the first column
print("First column:", array_2d[:, 0])

Second row: [40 50 60]
First column: [10 40]


In [14]:
# Slicing
# Creating a 1D array
array_1d= np.array ([10, 20, 30, 40, 50])
#Slicing elements from index 1 to 3
slice_1d = array_1d [1:4]
print("Sliced 1D Array (1:4):", slice_1d)

Sliced 1D Array (1:4): [20 30 40]


In [16]:
# Slicing elements from index 0 to 4 with a step of 2
slice_step_1d = array_1d [0:5:2]
print("Sliced 1D Array (0:5:2):", slice_step_1d) 

Sliced 1D Array (0:5:2): [10 30 50]


In [18]:
# Creating a 2D array
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Slicing a sub-array from the first two rows and columns
slice_2d = array_2d[:2, :2]

print("Sliced 2D Array:\n", slice_2d)

Sliced 2D Array:
 [[10 20]
 [40 50]]
